### ISSUE TITLE
Please Correct the Link

### ISSUE THREAD

**Issue by aljawaid** [ipunkt/KanboardCommentActions#3]
Hello, kindly correct the homelink and resubmit the plugin to the Kanboard Plugins directory.

https://github.com/ipunkt/KanboardCommentActions/blob/f7394fac5939765ff000fa05bdcbcce9661a38a4/Plugin.php#L77

The correct link should be `https://github.com/ipunkt/KanboardCommentActions`

**Comment by RainerBielefeld** [comment]
"[ipunkt Business Solutions OHG](https://www.northdata.de/ipunkt+Business+Solutions+OHG,+Ludwigsburg/Amtsgericht+Stuttgart+HRA+726262)" [does no longer exist](https://www.northdata.de/?id=5921577518). 

AFAIK:
* Bastian Rang now is  "Senior Product and Solution Architect", collaboration Factory AG, Ludwigsburg, Deutschland
* Robert Kummer now has his own " Robert Kummer IT"and also works at [iu](https://www.iu.de/)

If we do not get an answer here I will contact them. to ask them whether they still are interested in this plugin.

**Comment by aljawaid** [comment]
14 days is long enough to wait for an answer... I dont have time to go deep into looking at companies or chasing them up on the other side of the world.  I believe in circumstances like this, such plugins should be shown in the directory as 'archived' or unmaintained... but the Kanboard developer is not so open to such changes.
